# Main configuration for the Sophia v2 Agent

llm:
  # Model used by the agents. Using Flash for speed and cost-efficiency in MVP.
  model_name: "gemini-1.5-flash-latest"

vector_store:
  # Configuration for ChromaDB
  path: "data/chroma_db"

logging:
  # Configuration for application logging
  level: "INFO"
  file_path: "logs/sophia.log"
