# Konfigurace pro Sophia V4

# Režim spuštění: "online" (vyžaduje API klíč) nebo "offline" (používá mock LLM)
execution_mode: "online"

# Databáze pro epizodickou paměť a úkoly
database:
  db_host: "localhost"
  db_port: 5434 # Musí odpovídat portu vystavenému v docker-compose.yml
  db_user: "sophia_user"
  db_password: "sophia_password"
  db_name: "sophia_db"

logging:
  guardian_log: "logs/guardian.log"
  sophia_main_log: "logs/sophia_main.log"

# Nastavení životního cyklu
lifecycle:
  waking_duration_seconds: 10
  sleeping_duration_seconds: 5

# Konfigurace pro Large Language Models (LLM)
llm_models:
  default: economical
  llms:
    powerful:
      provider: "google"
      model_name: "gemini-1.5-pro-latest"
      api_key_env: "GEMINI_API_KEY"
      temperature: 0.7
      verbose: True
    economical:
      provider: "deepseek"
      model_name: "deepseek-coder-v2"
      api_key_env: "DEEPSEEK_API_KEY"
      temperature: 0.7
      verbose: True
    local:
      provider: "ollama"
      model_name: "llama3"
      temperature: 0.7
      verbose: True

# Konfigurace pro Intelligent Guardian
guardian:
  cpu_threshold: 90.0
  ram_threshold: 90.0