# Konfigurace pro Sophia V3

logging:
  guardian_log: "logs/guardian.log"
  sophia_main_log: "logs/sophia_main.log"

# Nastavení životního cyklu
lifecycle:
  waking_duration_seconds: 10
  sleeping_duration_seconds: 5

# Konfigurace pro Large Language Models (LLM)
# Struktura je navržena pro budoucí podporu více modelů.
llm_models:
  primary_llm:
    provider: "google" # 'google', 'openai', 'anthropic', atd.
    model_name: "gemini-2.5-flash"
    temperature: 0.7
    verbose: True
