# Konfigurace pro Sophia V4

# Režim spuštění: "online" (vyžaduje API klíč) nebo "offline" (používá mock LLM)
execution_mode: "online"

# Databáze pro epizodickou paměť a úkoly
database:
  db_host: "localhost"
  db_port: 5434 # Musí odpovídat portu vystavenému v docker-compose.yml
  db_user: "sophia_user"
  db_password: "sophia_password"
  db_name: "sophia_db"

logging:
  guardian_log: "logs/guardian.log"
  sophia_main_log: "logs/sophia_main.log"

# Nastavení životního cyklu
lifecycle:
  waking_duration_seconds: 10
  sleeping_duration_seconds: 5

# Konfigurace pro Large Language Models (LLM) přes OpenRouter
llm_models:
  # Výchozí model, který se použije, pokud není specifikován jiný.
  default: "google/gemini-2.5-flash-lite"

  # Seznam dostupných modelů s jejich OpenRouter identifikátory.
  # Pro každý model lze přidat specifickou konfiguraci, např. system_prompt.
  models:
    "google/gemini-2.5-flash-lite":
      # Pro tento model není potřeba žádná speciální konfigurace.
      # Bude použit globální system_prompt z 'prompts/system_prompt.txt'.
      pass

    "deepseek/deepseek-coder-v2":
      # Tento model je specializovaný na kódování.
      # Do budoucna zde může být specifický systémový prompt pro kódování.
      pass

    "deepseek/deepseek-v2-lite":
      # Další úsporný model od DeepSeek.
      pass

# Konfigurace pro Intelligent Guardian
guardian:
  cpu_threshold: 90.0
  ram_threshold: 90.0