# Konfigurace pro Sophia V4

# Režim spuštění: "online" (vyžaduje API klíč) nebo "offline" (používá mock LLM)
execution_mode: "online"

# Databáze pro epizodickou paměť a úkoly
database:
  db_host: "localhost"
  db_port: 5434
  db_user: "sophia_user"
  db_password: "sophia_password"
  db_name: "sophia_db"

logging:
  guardian_log: "logs/guardian.log"
  sophia_main_log: "logs/sophia_main.log"

# Konfigurace pro Large Language Models (LLM) přes OpenRouter
llm_models:
  # Výchozí model, který se použije, pokud není specifikován jiný.
  default: "economical"

  # Aliasy pro různé typy úkolů. Orchestrátor vybírá alias,
  # LLM Manager ho překládá na konkrétní model.
  aliases:
    powerful: "deepseek/deepseek-v3.2-exp"
    economical: "google/gemini-2.5-flash-lite"

  # Seznam dostupných modelů s jejich OpenRouter identifikátory.
  # Pro každý model lze přidat specifickou konfiguraci.
  # Prázdný slovník `{}` znamená, že se použije výchozí konfigurace.
  models:
    "google/gemini-2.5-flash-lite": {}
    "deepseek/deepseek-v3.2-exp": {}
    "anthropic/claude-3-haiku": {} # Přidán další model pro fallback

  # Seznam záložních modelů, které se použijí v případě selhání primárního modelu.
  # Budou se zkoušet v pořadí, v jakém jsou uvedeny.
  fallback_models:
    - "anthropic/claude-3-haiku"
    - "google/gemini-2.5-flash-lite" # Může být i zde jako poslední záchrana

# Konfigurace pro Orchestrator
orchestrator:
  # Maximální počet iterací (cyklů), než se agent zastaví.
  max_iterations: 100

# Konfigurace pro Orchestrator
orchestrator:
  # Maximální počet iterací (cyklů), než se agent zastaví.
  max_iterations: 100

# Konfigurace pro paměťový systém
memory:
  # Počet posledních interakcí, které se uchovávají v pracovní (krátkodobé) paměti.
  short_term_limit: 4
  # Počet nejrelevantnějších záznamů, které se načítají z dlouhodobé paměti.
  long_term_retrieval_limit: 5

# Konfigurace pro vektorovou databázi (ChromaDB)
vector_database:
  # Cesta k databázi. Může být lokální soubor nebo adresa serveru.
  path: "db/chroma.db"
  # Název kolekce, kde se budou ukládat paměťové záznamy.
  collection_name: "sophia_memory"

# Konfigurace pro Intelligent Guardian
guardian:
  cpu_threshold: 90.0
  ram_threshold: 90.0