llm:
  model: "openrouter/google/gemini-2.5-flash-lite-preview-09-2025"

plugins:
  interface_webui:
    host: "127.0.0.1"
    port: 8000

# Configuration for the File System Tool plugin
tool_file_system:
  sandbox_dir: "sandbox"

memory_chroma:
  db_path: "data/chroma_db"
