llm:
  model: "openrouter/meta-llama/llama-3.2-3b-instruct:free"  # Fast free model (2s response)
  api_key: "${OPENROUTER_API_KEY}" # SECURITY: API key from environment variable

plugins:
  interface_webui:
    host: "127.0.0.1"
    port: 8000

# Configuration for the File System Tool plugin
tool_file_system:
  sandbox_dir: "sandbox"

memory_chroma:
  db_path: "data/chroma_db"

tool_bash:
  timeout: 10 # Default timeout for shell commands in seconds

tool_web_search:
  google_api_key: "${GOOGLE_API_KEY}" # Handled by environment variable
  google_cse_id: "${GOOGLE_CSE_ID}" # Handled by environment variable

cognitive_doc_reader:
  docs_dir: "docs"

cognitive_historian:
  worklog_file: "WORKLOG.md"

cognitive_notes_analyzer:
  notes_file: "docs/roberts-notes.txt"
  enabled: true

# Jules API Tool - for delegating coding tasks to external AI agents
tool_jules_api:
  backend: "mock"  # Options: jules, copilot, claude, mock
  api_key: "${JULES_API_KEY}"  # Or GITHUB_COPILOT_KEY, ANTHROPIC_API_KEY
  endpoint: "https://jules.googleapis.com/v1"  # Backend-specific endpoint
  timeout: 300  # Task timeout in seconds
  max_retries: 3  # Maximum retry attempts
  poll_interval: 30  # Status polling interval in seconds

# Quality Assurance - INSTINKTY layer for code validation
cognitive_qa:
  min_compliance_score: 0.80  # Minimum score (0.0-1.0) to approve code
  allow_warnings: true  # Allow integration with warnings (not errors)
  require_tests: true  # Require test file for all plugins
  # Optional tool references (injected by PluginManager)
  # tool_llm: Reference to LLM tool for Level 3 deep review
  # tool_file_system: Reference to file system tool
  # tool_bash: Reference to bash tool for test execution

# Safe Integrator - INSTINKTY layer for atomic integration with rollback
cognitive_integrator:
  backup_dir: "data/backups"  # Directory for backup metadata
  auto_rollback: true  # Automatically rollback on integration failure
  require_tests_pass: true  # Require all tests to pass before integration
  backup_retention_days: 30  # Days to keep backup metadata
  # Tool references (injected by PluginManager)
  # tool_git: Reference to Git tool for backup/rollback operations
  # tool_bash: Reference to bash tool for test execution
  # tool_file_system: Reference to file system tool

# Security Monitor - Proactive security monitoring and anomaly detection
cognitive_security_monitor:
  enabled: true  # Enable/disable security monitoring
  report_interval_seconds: 60  # How often to generate summary reports
  alert_threshold: 3  # Number of events to trigger alert
  log_all_events: true  # Log every security event (verbose mode)
  monitor_file_integrity: true  # Enable periodic file integrity checks
  integrity_check_interval_minutes: 5  # How often to check file integrity

