llm:
  model: "openrouter/google/gemini-2.5-flash-lite-preview-09-2025"
  api_key: "${OPENROUTER_API_KEY}" # SECURITY: API key from environment variable

plugins:
  interface_webui:
    host: "127.0.0.1"
    port: 8000

# Configuration for the File System Tool plugin
tool_file_system:
  sandbox_dir: "sandbox"

memory_chroma:
  db_path: "data/chroma_db"

tool_bash:
  timeout: 10 # Default timeout for shell commands in seconds

tool_web_search:
  google_api_key: "${GOOGLE_API_KEY}" # Handled by environment variable
  google_cse_id: "${GOOGLE_CSE_ID}" # Handled by environment variable

cognitive_doc_reader:
  docs_dir: "docs"

cognitive_historian:
  worklog_file: "WORKLOG.md"

cognitive_notes_analyzer:
  notes_file: "docs/roberts-notes.txt"
  enabled: true

