name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Create Virtual Environment
        run: uv venv

      - name: Install dependencies
        # Spouštíme uv z virtuálního prostředí
        run: .venv/bin/uv pip sync requirements.in

      - name: Lint with ruff
        # Spouštíme ruff z virtuálního prostředí
        run: .venv/bin/ruff check .

      - name: Check formatting with ruff
        # A znovu...
        run: .venv/bin/ruff format --check .

      - name: Run tests
        # A nakonec i pytest
        run: PYTHONPATH=. .venv/bin/pytest
